### ISSUE TITLE
Error trying to create account on try.pinepods.online.

### ISSUE THREAD

**Issue by adamshand** [madeofpendletonwool/PinePods#203]
<img width="619" alt="image" src="https://github.com/madeofpendletonwool/PinePods/assets/130651/a2ece22d-e762-42eb-8e03-9eb18f315645">

**Comment by madeofpendletonwool** [comment]
Thanks for pointing this out! I quickly glanced at it here. Seems to be an inconsistency with postgres database return types. I'll have it fixed in no time!

**Comment by madeofpendletonwool** [comment]
Bug should be fixed. I just created a user. Thanks again for opening it! I'll keep an eye on it to ensure it doesn't pop up again. It's caused by an inconsistency in the psycopg return typing and it makes it difficult to test because of how inconsistent it is. Most of the time there's no issue, but sometimes it seems to just return data in a totally different way.

**Comment by adamshand** [comment]
Sorry, but I'm still getting the same error?

It might be because I chose a username with a `.` in it the first two times?  At least the third time when I created an account without a `.`, it worked.

<img width="609" alt="image" src="https://github.com/madeofpendletonwool/PinePods/assets/130651/a330f5ed-2c16-48a0-a9bc-e2ae8b205a1c">

**Comment by madeofpendletonwool** [comment]
You were right indeed, it was still due to that inconsistency. The characters were just a coincidence. That create user function calls two the database twice, I fixed it on one, the second call to the db has now also been fixed. I'll create about 10 users just to be safe and ensure they all work, but I think we're good at this point. Thanks again for opening the issue!
