### ISSUE TITLE
Admin credentials do not work with initial docker install

### ISSUE THREAD

**Issue by quetzalism** [madeofpendletonwool/PinePods#260]
Hi there, 

there seems to be an issue with the default admin credentials that are stored in the docker compose file. I have test both with mariadb and postgress. 

Steps to reproduce:

-create empty folder on desktop
-Use default docker-compose.yml (*either  DB Version) 
- docker compose up -d
- navigate to http://localhost:8040/ in web browser
-Enter the username and password from the environment section of the compose file

Result: "Your credentials appear to be incorrect"

Expected Result: Successful Login

Log: 

2024-08-12 11:42:12 Admin User Information:

2024-08-12 11:42:12 FULLNAME: Pinepods Admin
2024-08-12 11:42:12 USERNAME: admin
2024-08-12 11:42:12 EMAIL: evan@epiq.cc
2024-08-12 11:42:12 PASSWORD: securepass
2024-08-12 11:42:12          A
2024-08-12 11:42:12         d$b
2024-08-12 11:42:12       .d\$$b.
2024-08-12 11:42:12     .d$i$$\$$b.      _______   __                                                __
2024-08-12 11:42:12        d$$@b        /       \ /  |                                              /  |
2024-08-12 11:42:12       d\$$$ib       $$$$$$$  |$$/  _______    ______    ______    ______    ____$$ |  _______
2024-08-12 11:42:12     .d$$$\$$$b      $$ |__$$ |/  |/       \  /      \  /      \  /      \  /    $$ | /       |
2024-08-12 11:42:12   .d$$@$$$$\$$ib.   $$    $$/ $$ |$$$$$$$  |/$$$$$$  |/$$$$$$  |/$$$$$$  |/$$$$$$$ |/$$$$$$$/
2024-08-12 11:42:12       d$$i$$b       $$$$$$$/  $$ |$$ |  $$ |$$    $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |$$      \
2024-08-12 11:42:12      d\$$$$@$b.     $$ |      $$ |$$ |  $$ |$$$$$$$$/ $$ |__$$ |$$ \__$$ |$$ \__$$ | $$$$$$  |
2024-08-12 11:42:12   .d$@$$\$$$$$@b.   $$ |      $$ |$$ |  $$ |$$       |$$    $$/ $$    $$/ $$    $$ |/     $$/
2024-08-12 11:42:12 .d$$$$i$$$\$$$$$$b. $$/       $$/ $$/   $$/  $$$$$$$/ $$$$$$$/   $$$$$$/   $$$$$$$/ $$$$$$$/
2024-08-12 11:42:12         ###                                           $$ |
2024-08-12 11:42:12         ###                                           $$ |
2024-08-12 11:42:12         ###                                           $$/
2024-08-12 11:42:12 
2024-08-12 11:42:12 A project created and written by Collin Pendleton
2024-08-12 11:42:12 collinp@gooseberrydevelopment.com
2024-08-12 11:42:12 
2024-08-12 11:42:12 
2024-08-12 11:42:12 Using mysql/mariadb
2024-08-12 11:42:27 Error inserting or updating user: Not all parameters were used in the SQL statement
2024-08-12 11:42:27 Database Validation complete
2024-08-12 11:42:27 Backup of root's previous crontab saved to /root/.cache/crontab/crontab.bak
2024-08-12 11:42:27 2024-08-12 17:42:27,529 WARN For [program:crond], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2024-08-12 11:42:27 2024-08-12 17:42:27,529 WARN For [program:podcast_refresh], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2024-08-12 11:42:27 2024-08-12 17:42:27,529 WARN For [program:client_api], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2024-08-12 11:42:27 2024-08-12 17:42:27,529 WARN For [program:main_app], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
2024-08-12 11:42:27 2024-08-12 17:42:27,529 INFO Set uid to user 0 succeeded
2024-08-12 11:42:27 2024-08-12 17:42:27,530 INFO supervisord started with pid 112
2024-08-12 11:42:28 2024-08-12 17:42:28,532 INFO spawned: 'client_api' with pid 113
2024-08-12 11:42:28 2024-08-12 17:42:28,534 INFO spawned: 'crond' with pid 114
2024-08-12 11:42:28 2024-08-12 17:42:28,535 INFO spawned: 'main_app' with pid 115
2024-08-12 11:42:28 2024-08-12 17:42:28,536 INFO spawned: 'podcast_refresh' with pid 116
2024-08-12 11:42:29 2024-08-12 17:42:29,537 INFO success: client_api entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-12 11:42:29 2024-08-12 17:42:29,537 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-12 11:42:29 2024-08-12 17:42:29,537 INFO success: main_app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-08-12 11:42:38 2024-08-12 17:42:38,541 INFO success: podcast_refresh entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2024-08-12 11:42:38 2024-08-12 17:42:38,564 INFO exited: podcast_refresh (exit status 0; expected)
2024-08-12 11:42:12 wait-for-it.sh: waiting 60 seconds for db:3306
2024-08-12 11:42:26 wait-for-it.sh: db:3306 is available after 14 seconds
2024-08-12 11:42:27 2024-08-12 17:42:27,334 - ERROR - Error inserting or updating user: Not all parameters were used in the SQL statement
2024-08-12 11:42:27 2024-08-12 17:42:27,338 - ERROR - Database error: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`pinepods_database`.`apikeys`, CONSTRAINT `apikeys_ibfk_1` FOREIGN KEY (`UserID`) REFERENCES `Users` (`UserID`) ON DELETE CASCADE)
2024-08-12 11:42:27 chown: unknown user/group Debian-exim:Debian-exim
2024-08-12 11:42:27 chown: unknown user/group Debian-exim:Debian-exim

**Comment by madeofpendletonwool** [comment]
Great find again, this was due to a recent adjustment made of the background task username which broke user insertion. Fixed in #265

**Comment by xakaitetoia** [comment]
Hello, Is this expected to be fixed on new version? I still have issues with docker-compose file
