### ISSUE TITLE
Unable to login with MFA/2FA enabled on PinePods 0.8.2 (Linux & Windows) but works fine on Android

### ISSUE THREAD

**Issue by IoSonoPiero** [madeofpendletonwool/PinePods#721]
I'm experiencing a login issue on PinePods version **0.8.2** when using **Linux** or **Windows**:  
If the user has enabled MFA/2FA, logging in to the desktop client always fails (authentication process doesn't work or the second factor isn't requested).

**Details:**
- **PinePods Version:** 0.8.2
- **Operating Systems:** tested on both Linux and Windows
- **MFA/2FA:** enabled on the account

**Important Note:**  
On **Android** the login works fine even with MFA/2FA enabled, so the problem seems to affect desktop clients only.

**Additional Observation:**  
If the first login on Windows or Linux is performed with MFA/2FA disabled, and MFA/2FA is enabled afterward from within the application while already logged in, at the next application start the user remains logged in.

Is this an intended behavior or a bug?

**Steps to Reproduce:**
1. Enable MFA/2FA on the PinePods account
2. Try logging in with PinePods 0.8.2 on Linux or Windows
3. Login fails, even though username and password are correct

**Alternative Scenario:**
1. Login on the desktop client with MFA/2FA disabled
2. Enable MFA/2FA from the application while logged in
3. Close and restart the application
4. User is still logged in without being prompted for MFA/2FA

**Expected Behavior:**  
Second factor should be requested and login should succeed.

**Actual Behavior:**  
Login fails or authentication loops without requesting the second factor.  
After enabling MFA/2FA post-login, user remains logged in after restarting the application.

**Logs/Screenshots:**
see attached screenshot for the error message I got when MFA is enabled.

<img width="521" height="121" alt="Image" src="https://github.com/user-attachments/assets/f917570f-c7eb-473b-96f4-e7165cffb97e" />

**Comment by madeofpendletonwool** [comment]
Thanks for opening the issue. I think there is a bug of some sort going on. I will dig in further and sort it out for the next release.

**Comment by madeofpendletonwool** [comment]
With 0.9.0 this issue is fixed. I've done a lot of confirmation with MFA to ensure things work.

**Comment by IoSonoPiero** [comment]
Hello, sorry for late reply!

Still reproducible on 0.9.0 (rpm, x86_64), Linux desktop.

Steps:
1. Enter server URL, username, password (MFA enabled on account)
2. Client never prompts for MFA/TOTP code
3. Immediately shows "Your credentials appear to be incorrect"

Same behavior as originally reported on 0.8.2 — the second factor is never requested.

For comparison: login on Android (same account, same credentials) works correctly and does prompt for the MFA token.

Can you confirm the fix actually landed in the 0.9.0 release build, or if it's only on main post-tag?

I tried RPM and AppImage.

**Comment by madeofpendletonwool** [comment]
Oh! You're actually using the desktop downloaded app. I misunderstood that. Okay, I will test that and get it sorted.
